version: 2.1

jobs:
  test:
    working_directory: ~/caotico
    docker:
      - image: cimg/ruby:4.0
        environment:
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: cimg/postgres:14
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: caotico_test
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
            - v1-bundle-

      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:prepare

      - run:
          name: Run tests
          command: bin/rails test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
