# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d80d0a672018ab87042ffa5d5214eb6c6a783948bb50109ae0c355f0890c593a14f6125bf8b86d8a4df92f2a315ec8c8d1f6da031724b3de57e2fe105666df4f

test:
  secret_key_base: 754421079984fa0ab188874fc587250772a90de847757160f01a2f59f7877507d72ab62ec408435459cea07e06f6fc75f4a702beb52a0c81486ea3376c54e94a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_analytics_tracking_id: <%= ENV["GOOGLE_ANALYTICS_TRACKING_ID"] %>
